---
# MinecraftPE MP ec2 
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    key: 'db'
    instance_type: 'm1.small'
    region: 'us-east-1'
    subnet: 'subnet-f849ff96'
    ec2_instances:
      - name: 'minecraftpe-mp'
        tags: ['foo', 'bar']
        group_id: 'sg-dfe6c6a6'
        image: 'ami-bcb853d1'
        ssh_user: 'ubuntu'
  tasks:
  - name: Create Ec2 Instance
    local_action:
      module: ec2
      key_name: "{{ key }}"
      instance_tags: {Name: "{{ item.name }}"}
      group_id: "{{ item.group_id }}"
      instance_type: "{{ instance_type }}"
      region: "{{ region }}"
      image: "{{ item.image }}"
      wait: yes
      count: 1
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: yes
    register: ec2_info 
    with_items: "{{ec2_instances}}"

    #- debug: var=ec2_info
    #with_items: "{{ec2_info.results}}"
    #- debug: var=item
    #with_items: "{{ec2_info.results}}"


  - add_host: hostname="{{ item.instances[0].public_ip }}" groupname=minecraftpe
    with_items: "{{ec2_info.results}}"

  - name: wait for instances to listen on port:22
    wait_for:
      state: started
      host: "{{ item.instances[0].public_ip }}"
      port: 22
    with_items: "{{ec2_info.results}}"
  
- hosts: minecraftpe
  gather_facts: False
  remote_user: 'ubuntu'
  # Run as sudo
  become: True
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  tasks:
    - name: Upgrade the Distro
      apt: upgrade=dist

    - name: Install packages
      apt: name=git state=present

    - name: Clone the MinecraftPE-MP server code
      git: repo=https://github.com/PocketMine/PocketMine-MP.git dest=/home/ubuntu recursive=true

    - name: Pull in and extract the correct php7 binary
      raw: cd /home/ubuntu/PocketMine-MP && wget https://bintray.com/pocketmine/PocketMine/download_file?file_path=PHP_7.0.3_x86-64_Linux.tar.gz && tar -xf download_file?file_path=PHP_7.0.3_x86-64_Linux.tar.gz && rm download_file?file_path=PHP_7.0.3_x86-64_Linux.tar.gz

    - name: Copy over the server.properties
      copy: src=../templates/server.properties dest=/home/ubuntu/PocketMine-MP/server.properties owner=ubuntu group=ubuntu mode="u=rw,g=r,o=r"

    - name: Start the server
      raw: cd /home/ubunut/PocketMine-MP && ./start.sh
