---
# MinecraftPE MP ec2 
- hosts: localhost
  gather_facts: False
  vars:
  - key: db
  - name: minecraftpe-mp
  - instance_type: m1.small
  - security_group: sg-dfe6c6a6
  - image: ami-bcb853d1
  - region: us-east-1
  - subnet: subnet-f849ff96
  tasks:
  - name: Create Ec2 Instance
    local_action:
      module: ec2
      key_name: "{{ key }}"
      instance_tags: {Name: "{{ name }}"}
      group_id: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      region: "{{ region }}"
      image: "{{ image }}"
      wait: yes
      count: 1
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: yes
      register: output
  - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
  - name: Echo the IP Address
  - debug: msg="the output was {{ output.stdout }}"
