---
# MinecraftPE MP ec2 
- hosts: localhost
  gather_facts: False
  vars:
  - key: db
  - name: minecraftpe-mp
  - instance_type: m1.small
  - security_group: sg-dfe6c6a6
  - image: ami-bcb853d1
  - region: us-east-1
  - subnet: subnet-f849ff96
  tasks:
  - name: Create Ec2 Instance
    local_action:
      module: ec2
      key_name: "{{ key }}"
      instance_tags: {Name: "{{ name }}"}
      group_id: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
      region: "{{ region }}"
      image: "{{ image }}"
      wait: yes
      count: 1
      vpc_subnet_id: "{{ subnet }}"
      assign_public_ip: yes
    register: ec2_instance 
  - name: Set the Instances facts
    set_fact:
      instance_public_ip_1: "{{ ec2_instance.results[0].instances[0].public_ip }}"
      instance_id_1: "{{ ec2_instance.results[0].instances[0].id }}"
  - name: Add the newly created EC2 instance to the local host group (located inside the directory)
    local_action: 
      module: lineinfile 
      dest: "./hosts" 
      regexp: "{{ item }}" 
      insertafter: "[minecraft-server]" 
      line: "{{ item }}"
    with_items:
      - "{{ instance_public_ip_1 }}"
  - name: Wait for SSH to come up
    local_action: 
      module: wait_for 
      host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
      port: 22 
      state: started
      search_regex: OpenSSH
      delay: 10

- hosts: minecraft-server
  sudo: True
  remote_user: ubuntu
  gather_facts: True
  tasks:
    - name: Get Ip Address
      local_action:
        module: shell
        shell: ifconfig | grep inet
        register: if_output
        debug: msg="the output was {{ if_output.stdout }}"
